/** ***************************************************************************
 * @mainpage Moodlight
 *
 * is the subject of the <b>Electonics-Project (ETP)</b>
 * starting with fall term 2020
 * in the <b>third year of the electronics engineering part-time curriculum</b>
 * at the School of Engineering of the Zurich University of Applied Sciences.
 * 
 * Colour space approximated with power LEDs (white, amber, red, green and blue)
 * @image html colour_space_LEDs.png
 *
 *
 * LEDs driven by HW (step-down converter) and microcontroller SW (written in C)
 * @image html board-small.png
 *
 * User interface on microcontroller evalboard:
 * pushbuttons to chose colour and mode,
 * touchslider to change value and touchgecko to restart (or stop)
 * @image html gecko.png
 *
 * For solution specific description see powerLEDs.c
 *
 * Remote control over serial interface with a protocol based on command strings
 * @image html putty.png
 *
 * User interface as smartphone app (written in Java) which uses the serial protocol over Bluetooth
 * @image html app.png
 * 
 * Colours may be: white, amber, red, green and blue<br>
 * Colour space preferably: hue, saturation, lightness<br>
 * Modes could be: midday, sunset moodlight, submarine, doze, awake, party, yoga, ...
 *
 *
 * Board:  Starter Kit EFM32-G8XX-STK
 * Device: EFM32G890F128 (Gecko)
 *
 * <b>Coding guidelines</b>
 * The official coding guidelines of GNOME were followed. For detailed information, visit:
 * <a href="https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en">GNOME Coding Guidelines</a>
 *
 * <b>Table of Contents</b>
 *  - List of files
 *  - Globals
 *  - Todo list
 *  - Documentation of tests
 *
 * @author schmiaa1@students.zhaw.ch, bodenma2@students.zhaw.ch
 * @date 14.12.2020
 *****************************************************************************/

/**
 * @page Page Documentation of tests
 *
 * The software was only tested together with the hardware.
 *
 * <b>Solution 3:</b><br/>
 * Before the full connection with the circuit, the DAC0 CH0 and TIMER0 PWM signal was measured for safety reasons.
 * After connecting the microcontroller to the circuit following tests were made:
 * - Adjusting touchslider position results in voltage change over power resistor
 * - current does never exceed the upper limit. (adjustable from 0mA to 350mA)
 *
 * <b>Solution 4:</b><br/>
 * Before the full connection with the circuit, the DAC0 CH1 was measured for safety reasons.
 * After connecting the microcontroller to the circuit following tests were made:
 * - PWM signal generated by timer interrupt and ACMP had the desired duty cycle
 * - Adjusting touchslider position results in voltage change over power resistor
 * - current does never exceed the upper limit. (adjustable from 80mA to 350mA)
 */

/** ***************************************************************************
 * @file
 * @brief main file for the Moodlight
 *
 * Sets up uC, clocks, peripherals and user interface.
 * Starts the powerLEDs, etc.
 *
 * Loops in the user interface
 *
 * @author schmiaa1@students.zhaw.ch, bodenma2@students.zhaw.ch
 * @date 14.12.2020
 *****************************************************************************/ 


#include "em_chip.h"
#include "em_device.h"
#include "em_system.h"
#include "em_cmu.h"
#include "em_emu.h"

#include "segmentlcd.h"

#include "globals.h"
#include "communication.h"
#include "pushbuttons.h"
#include "powerLEDs.h"
#include "touchslider.h"
#include "userinterface.h"
#include "signalleds.h"


/******************************************************************************
 * Defines
 *****************************************************************************/
 


/******************************************************************************
 * Variables
 *****************************************************************************/



/******************************************************************************
 * Functions
 *****************************************************************************/


/**************************************************************************//**
 * @brief main function
 *
 * @return nothing, as it runs in an endless loop
 * Sets up uC, clocks, peripherals and user interface.
 * Waits in low energy mode for an interrupt.
 *****************************************************************************/
int main(void) {
  CHIP_Init();                  		// Chip revision alignment and errata fixes
  INIT_XOclocks();						// Start crystal oscillators

  COM_Init();							// Initialize serial communication

  PB_Init();							// Initialize the pushbuttons
  PB_EnableIRQ();						// and enable pushbuttons interrupts

  SL_Init();							// Initialize the signal LEDs

  CAPSENSE_Init();						// Init touch slider and touch gecko

  SegmentLCD_Init(false);				// Initialize the LCD
  SegmentLCD_Write("PowerUp");
  SegmentLCD_Number(0);

  PWR_init();							// Initialize the power LEDs

  while(1) {							// loop forever
	  SL_Toggle(SL_3_PORT, SL_3_PIN);	// can be used for oscilloscope synch.
	  UI_FSM_event();					// check for events
	  UI_FSM_state_value();				// handles the events
	  lightOnOrOff();
  }
}
